# PHP Settings
php_version:  "8.1"
wp_version: "6.6.1"
php_modules: [ 'php8.1-curl', 'php8.1-gd', 'php8.1-mbstring', 'php8.1-xml', 'php8.1-xmlrpc', 'php8.1-soap', 'php8.1-intl', 'php8.1-zip' ]
env_production: 
 - cochlearmaia
 - plataform
env_homolog:
 - maia1
 - maia2
 - maia3
 - intro 
  
